services:
  postgres:
    image: postgres:15
    container_name: survey_postgres
    restart: always
    environment:
      POSTGRES_USER: survey_user
      POSTGRES_PASSWORD: survey_password
      POSTGRES_DB: survey_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: survey_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: